### PR TITLE
added AccountTest to problem with @Column on Postgres

### PR DESCRIPTION
**Pull request by buckfeng**
The AccountTest failed due to `@Column(name="ID")` annotation on the Account entity class with the following error.  It affected postgres only, not oracle and sql server.

```
18:24:13.881 [main] INFO  io.ebean.DDL - Executing db-create-all.sql - 2 statements, autoCommit:false
18:24:13.882 [main] DEBUG io.ebean.DDL - executing 1 of 2 create table account (   id                            bigint generated by defau...
18:24:13.894 [main] DEBUG io.ebean.DDL - executing 2 of 2 create table customer (   id                            bigint generated by defa...
18:24:13.911 [main] DEBUG io.ebean.SQL - txn[1001] insert into account (name, notes, version) values (?,?,?); -- bind(Rob,null,1)
18:24:13.918 [main] DEBUG io.ebean.SUM - txn[1001] Error[ERROR: column "ID" does not exist   Position: 72]
18:24:13.918 [main] TRACE io.ebean.TXN - txn[1001] Commit - query only

javax.persistence.PersistenceException: Error[ERROR: column "ID" does not exist   Position: 72]

	at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:55)
	at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:231)
```

### CODE REVIEW

**Comment by rbygrave** [comment]
Does this reproduce without the `useDocker: false` ... does it reproduce against vanilla postgres.

**Comment by buckfeng** [comment]
Yes.  The reported issue can be reproduced with a local instance of postgres (v11).

Separately, I couldn't get test with docker to work (useDocker: true) even with the latest ebean v12.3.3 from Maven.

**Comment by rbygrave** [comment]
I suggest that this will not reproduce (Postgres dictionary is by default not case sensitive).  Note taht once I run this and it does not reproduce then it will be up to you to create a reproducing test case or close the issue.

**Comment by buckfeng** [comment]
I finally got the docker-ebean-test to work and pushed the changes.  The reported issue can be reproduced.

As it turned out that the password was "admin", not "postgres".  who'd have guessed? :-)

**Comment by buckfeng** [comment]
Issue closed.

**Pull request closed without merging**
