### PR TITLE
Serialization bug when using entity from other database persistence

### PR DESCRIPTION
**Pull request by fyrnaga**
After upgrading to 12.16.1 or 13.6.1, we get the following error:

```
09:19:03.419 [ebean-db1] TRACE io.ebean.BackgroundExecutor - Stop io.ebeaninternal.server.transaction.PostCommitProcessing$$Lambda$366/0x0000000800354440@abbc908 (exec time 123 us)

javax.persistence.PersistenceException: Query threw SQLException:ERROR: relation "notification_categories" does not exist
  Position: 75 Bind values:[1, ] Query was:select t0.id, t0.organization_id, t0.name, t0.created_at, t0.version from notification_categories t0 where t0.id = ?

	at io.ebean.config.dbplatform.SqlCodeTranslator.translate(SqlCodeTranslator.java:80)
	at io.ebean.config.dbplatform.DatabasePlatform.translate(DatabasePlatform.java:245)
	at io.ebeaninternal.server.query.CQueryEngine.translate(CQueryEngine.java:138)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.translate(DefaultOrmQueryEngine.java:43)
	at io.ebeaninternal.server.core.OrmQueryRequest.translate(OrmQueryRequest.java:58)
	at io.ebeaninternal.server.query.CQuery.createPersistenceException(CQuery.java:643)
	at io.ebeaninternal.server.query.CQueryEngine.find(CQueryEngine.java:403)
	at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findId(DefaultOrmQueryEngine.java:175)
	at io.ebeaninternal.server.core.OrmQueryRequest.findId(OrmQueryRequest.java:345)
	at io.ebeaninternal.server.core.DefaultServer.findId(DefaultServer.java:1111)
	at io.ebeaninternal.server.core.DefaultServer.findOne(DefaultServer.java:1128)
	at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findOne(DefaultOrmQuery.java:1509)
	at io.ebeaninternal.server.core.DefaultBeanLoader.refreshBeanInternal(DefaultBeanLoader.java:229)
	at io.ebeaninternal.server.core.DefaultBeanLoader.loadBean(DefaultBeanLoader.java:163)
	at io.ebeaninternal.server.core.DefaultServer.loadBean(DefaultServer.java:554)
	at io.ebean.bean.SingleBeanLoader$Dflt.loadBean(SingleBeanLoader.java:70)
	at io.ebean.bean.InterceptReadWrite.loadBeanInternal(InterceptReadWrite.java:734)
	at io.ebean.bean.InterceptReadWrite.loadBean(InterceptReadWrite.java:706)
	at io.ebean.bean.InterceptReadWrite.preGetter(InterceptReadWrite.java:829)
	at org.example.domain.NotificationCategory._ebean_get_organizationId(NotificationCategory.java:6)
	at org.example.domain.NotificationCategory.getOrganizationId(NotificationCategory.java:40)
	at org.example.domain.DeserializationIssueTest.insertCategoryAndDeserializeNotificationFromJson(DeserializationIssueTest.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.postgresql.util.PSQLException: ERROR: relation "notification_categories" does not exist
  Position: 75
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:181)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:133)
	at io.ebean.datasource.pool.ExtendedPreparedStatement.executeQuery(ExtendedPreparedStatement.java:120)
	at io.ebeaninternal.server.query.CQuery.prepareResultSet(CQuery.java:331)
	at io.ebeaninternal.server.query.CQuery.prepareBindExecuteQueryWithOption(CQuery.java:288)
	at io.ebeaninternal.server.query.CQuery.prepareBindExecuteQuery(CQuery.java:284)
	at io.ebeaninternal.server.query.CQueryEngine.find(CQueryEngine.java:387)
	... 82 more

09:19:03.461 [EbeanHook] DEBUG io.ebean - Ebean shutting down
```

It seems it is linked to the fact that it is trying to bind it right away to the database, but there was no fetch nor persistence.

### CODE REVIEW

**Comment by rbygrave** [comment]
> PSQLException: ERROR: relation "notification_categories" does not exist

Well, that is down to the test setup here which is "kind of odd":

- There are 2 databases defined "db" and "otherdb" ?  but really there is only 1 database needed/used by the test here
- Both are setup to use the same username.  That isn't correct unless it also explicitly modifies the postgres search path (which it doesn't do).
- Also the tables in question are being created by manually?  rather than declaratively via application-test.yaml ddlMode dropCreate ?  

I'm thinking this is maybe due to this code coming from play-ebean which has imo fairly odd testing setup.

**Comment by rbygrave** [comment]
So fixing that test setup, fixing the enhancement tile version `<tile>io.ebean.tile:enhancement:13.6.1</tile>` we end up with:

```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DeserializationIssueTest.insertCategoryAndDeserializeNotificationFromJson:66 expected: <null> but was: <1>
```

**Comment by rbygrave** [comment]
Patch:

```
Index: src/test/java/org/example/domain/DeserializationIssueTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/test/java/org/example/domain/DeserializationIssueTest.java b/src/test/java/org/example/domain/DeserializationIssueTest.java
--- a/src/test/java/org/example/domain/DeserializationIssueTest.java	(revision 52410892ce2f1e4730561eb318d0decc3a0232ae)
+++ b/src/test/java/org/example/domain/DeserializationIssueTest.java	(date 1659312832290)
@@ -18,51 +18,52 @@
   @Test
   void insertCategoryAndDeserializeNotificationFromJson() {
 
-    Database server = DB.byName("otherdb");
-    CallableSql callableSql = server.createCallableSql("BEGIN;\n" +
-      "DROP TABLE IF EXISTS notifications;\n" +
-      "DROP TABLE IF EXISTS notification_categories;\n" +
-      "CREATE TABLE notification_categories (\n" +
-      "\tid serial not null,\n" +
-      "\torganization_id bigint,\n" +
-      "\tname character varying(255),\n" +
-      "\tcreated_at timestamp with time zone NOT NULL,\n" +
-      "\t\"version\" bigint NOT NULL,\n" +
-      "\tPRIMARY KEY(id)\n" +
-      ");\n" +
-      "\n" +
-      "CREATE TABLE notifications (\n" +
-      "\tid serial NOT NULL,\n" +
-      "\tmessage character varying(255),\n" +
-      "\tcategory_id bigint,\n" +
-      "\tcreated_at timestamp with time zone NOT NULL,\n" +
-      "\t\"version\" bigint NOT NULL,\n" +
-      "\tPRIMARY KEY(id)\n" +
-      ");\n" +
-      "\n" +
-      "ALTER TABLE IF EXISTS notifications\n" +
-      "\tADD CONSTRAINT fk_notifications_category_id\n" +
-      "\tFOREIGN KEY (category_id)\n" +
-      "\tREFERENCES notification_categories (id)\n" +
-      "\tON DELETE RESTRICT\n" +
-      "\tON UPDATE RESTRICT;\n" +
-      "\t\n" +
-      "COMMIT;\n" +
-      "\n");
-    server.execute(callableSql);
+//    Database server = DB.byName("otherdb");
+//    CallableSql callableSql = server.createCallableSql("BEGIN;\n" +
+//      "DROP TABLE IF EXISTS notifications;\n" +
+//      "DROP TABLE IF EXISTS notification_categories;\n" +
+//      "CREATE TABLE notification_categories (\n" +
+//      "\tid serial not null,\n" +
+//      "\torganization_id bigint,\n" +
+//      "\tname character varying(255),\n" +
+//      "\tcreated_at timestamp with time zone NOT NULL,\n" +
+//      "\t\"version\" bigint NOT NULL,\n" +
+//      "\tPRIMARY KEY(id)\n" +
+//      ");\n" +
+//      "\n" +
+//      "CREATE TABLE notifications (\n" +
+//      "\tid serial NOT NULL,\n" +
+//      "\tmessage character varying(255),\n" +
+//      "\tcategory_id bigint,\n" +
+//      "\tcreated_at timestamp with time zone NOT NULL,\n" +
+//      "\t\"version\" bigint NOT NULL,\n" +
+//      "\tPRIMARY KEY(id)\n" +
+//      ");\n" +
+//      "\n" +
+//      "ALTER TABLE IF EXISTS notifications\n" +
+//      "\tADD CONSTRAINT fk_notifications_category_id\n" +
+//      "\tFOREIGN KEY (category_id)\n" +
+//      "\tREFERENCES notification_categories (id)\n" +
+//      "\tON DELETE RESTRICT\n" +
+//      "\tON UPDATE RESTRICT;\n" +
+//      "\t\n" +
+//      "COMMIT;\n" +
+//      "\n");
+//    server.execute(callableSql);
 
     NotificationCategory category = new NotificationCategory();
     category.setName("testCategory");
     category.setOrganizationId(1L);
 
-    server.save(category);
+    DB.save(category);
 
     assertNotNull(category.getOrganizationId());
 
     String notificationJson = "{ \"message\": \"test message\", \"category\": { \"id\" : 1 } }";
-    Notification notification = server.json().toBean(Notification.class, notificationJson);
+    Notification notification = DB.json().toBean(Notification.class, notificationJson);
 
-    assertNull(notification.getCategory().getOrganizationId());
+    NotificationCategory category1 = notification.getCategory();
+    assertNull(category1.getOrganizationId());
   }
 
 }
Index: pom.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pom.xml b/pom.xml
--- a/pom.xml	(revision 52410892ce2f1e4730561eb318d0decc3a0232ae)
+++ b/pom.xml	(date 1659313120820)
@@ -91,7 +91,7 @@
         <configuration>
           <tiles>
             <tile>org.avaje.tile:java-compile:11</tile>
-            <tile>io.ebean.tile:enhancement:12.11.1</tile>
+            <tile>io.ebean.tile:enhancement:13.6.1</tile>
           </tiles>
         </configuration>
       </plugin>
Index: src/main/resources/application.properties
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>ISO-8859-1
===================================================================
diff --git a/src/main/resources/application.properties b/src/main/resources/application.properties
--- a/src/main/resources/application.properties	(revision 52410892ce2f1e4730561eb318d0decc3a0232ae)
+++ b/src/main/resources/application.properties	(date 1659313315417)
@@ -9,13 +9,13 @@
 ## define these in external properties ...
 
 datasource.db.username=db
-datasource.db.password=test
-datasource.db.databaseUrl=jdbc:postgresql://localhost:6432/db
-datasource.db.databaseDriver=org.postgresql.Driver
+datasource.db.password=change-me-sometime
+datasource.db.databaseUrl=jdbc:postgresql://localhost:6432/change_me_also
 
-datasource.otherdb.username=db
-datasource.otherdb.password=test
-datasource.otherdb.databaseUrl=jdbc:postgresql://localhost:6432/otherdb
-datasource.otherdb.databaseDriver=org.postgresql.Driver
+
+#datasource.otherdb.username=db
+#datasource.otherdb.password=test
+#datasource.otherdb.databaseUrl=jdbc:postgresql://localhost:6432/otherdb
+#datasource.otherdb.databaseDriver=org.postgresql.Driver
 
 
Index: src/test/resources/application-test.yaml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/test/resources/application-test.yaml b/src/test/resources/application-test.yaml
--- a/src/test/resources/application-test.yaml	(revision 52410892ce2f1e4730561eb318d0decc3a0232ae)
+++ b/src/test/resources/application-test.yaml	(date 1659313018055)
@@ -3,12 +3,12 @@
 #    useDocker: false
 #    shutdown: stop # stop | remove
     platform: postgres # h2, postgres, mysql, oracle, sqlserver, sqlite
-    ddlMode: none # none | dropCreate | create | migration | createOnly | migrationDropCreate
-    dbName: db
-    username: db
-    password: test
-    extraDb:
-      dbName: otherdb
-      username: db
-      password: test
+    ddlMode: dropCreate # none | dropCreate | create | migration | createOnly | migrationDropCreate
+    dbName: my_test
+#    username: db
+#    password: test
+#    extraDb:
+#      dbName: otherdb
+#      username: otherdb
+#      password: test
 
Index: src/test/resources/logback-test.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/test/resources/logback-test.xml b/src/test/resources/logback-test.xml
--- a/src/test/resources/logback-test.xml	(revision 52410892ce2f1e4730561eb318d0decc3a0232ae)
+++ b/src/test/resources/logback-test.xml	(date 1659312776050)
@@ -28,7 +28,7 @@
   </root>
 
 
-  <logger name="io.ebean" level="TRACE"/>
+<!--  <logger name="io.ebean" level="TRACE"/>-->
 
   <!-- sql and transaction logging -->
   <logger name="io.ebean.SQL" level="TRACE"/>
```

**Comment by fyrnaga** [comment]
> > PSQLException: ERROR: relation "notification_categories" does not exist
> 
> Well, that is down to the test setup here which is "kind of odd":
> 
> * There are 2 databases defined "db" and "otherdb" ?  but really there is only 1 database needed/used by the test here
> * Both are setup to use the same username.  That isn't correct unless it also explicitly modifies the postgres search path (which it doesn't do).
> * Also the tables in question are being created by manually?  rather than declaratively via application-test.yaml ddlMode dropCreate ?
> 
> I'm thinking this is maybe due to this code coming from play-ebean which has imo fairly odd testing setup.

I know this setup seems a bit odd, but it kinda reflects the setup we have in our application. In our app, we have 3 datasources/db setup and entities spread across them. When we upgrade, we faced issues with entities which are not linked to the default datasource/db. That is why the test is using only the `otherdb` to illustrate the problem with the entities not attached to the default datasource.

I had some trouble setting the example since it is the first time I tried to do test with ebean-test. We leverage flyway for the db schema creation in our app. We also use the same user for our 3 mysql database, to separate the database (retention, criticality).

We don't use the annotation for the database name since it could change depending on the environment. As well, if I used the application-test.yaml ddlMode, it would have created the schema in the default database, which is not what i wanted. to illustrate the problem we are facing.

**Comment by fyrnaga** [comment]
@rbygrave Thanks for the fix that you done in version 12.17.0, it fixed it.

**Pull request closed without merging**
